# Stage 1: Frontend Build
FROM oven/bun:latest AS frontend-build

WORKDIR /mental-health

# Copy all packages and apps
COPY ./packages ./packages
COPY ./apps ./apps

# Copy root monorepo config
COPY package.json bun.lock ./

# Navigate to frontend directory
WORKDIR /mental-health/apps/frontend

# Install and build frontend
RUN bun install
RUN bun run build

# Stage 2: Backend Setup
FROM oven/bun:latest

WORKDIR /app

# Copy root monorepo config
COPY package.json bun.lock ./

# Copy all packages
COPY ./packages ./packages
COPY ./apps ./apps

# Copy root monorepo config
COPY package.json bun.lock ./



# Copy built frontend from frontend-build stage
COPY --from=frontend-build /mental-health/apps/frontend/build ./apps/backend-api/build

# Copy migrations
COPY ./packages/backend/migrations ./apps/backend-api/migrations

# Install backend dependencies
WORKDIR /app/apps/backend-api
RUN bun install



# Command to start the application
CMD ["bun", "run", "start"]



